namespace NetEvolve.Pulse.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Options;
using NetEvolve.Pulse.Extensibility.Outbox;
using NetEvolve.Pulse.Outbox;

/// <summary>
/// Entity Framework Core configuration for <see cref="OutboxMessage"/> targeting PostgreSQL.
/// Uses double-quoted identifiers in index filter expressions as required by PostgreSQL syntax.
/// </summary>
/// <remarks>
/// <para><strong>Filter Syntax:</strong></para>
/// PostgreSQL requires double-quoted identifiers in raw SQL expressions, e.g. <c>"Status"</c>.
/// Using unquoted names would cause PostgreSQL to lowercase them, which would not match
/// the Pascal-cased column names generated by EF Core's default conventions.
/// <para><strong>Usage:</strong></para>
/// Either instantiate this class directly or call
/// <see cref="ModelBuilderExtensions.ApplyPulseConfiguration{TContext}(ModelBuilder, TContext)"/>
/// with the Npgsql provider name.
/// <para><strong>Customization:</strong></para>
/// Override schema and table names via <see cref="OutboxOptions"/> before applying this configuration.
/// </remarks>
/// <example>
/// <code>
/// protected override void OnModelCreating(ModelBuilder modelBuilder)
/// {
///     // Directly
///     modelBuilder.ApplyConfiguration(new PostgreSqlOutboxMessageConfiguration());
///
///     // Via extension method (recommended)
///     modelBuilder.ApplyPulseConfiguration(this);
/// }
/// </code>
/// </example>
internal sealed class PostgreSqlOutboxMessageConfiguration : OutboxMessageConfigurationBase
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PostgreSqlOutboxMessageConfiguration"/> class with default options.
    /// </summary>
    public PostgreSqlOutboxMessageConfiguration()
        : this(Options.Create(new OutboxOptions())) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="PostgreSqlOutboxMessageConfiguration"/> class.
    /// </summary>
    /// <param name="options">The outbox options containing schema and table configuration.</param>
    public PostgreSqlOutboxMessageConfiguration(IOptions<OutboxOptions> options)
        : base(options) { }

    /// <inheritdoc />
    protected override string PendingMessagesFilter =>
        $"\"{OutboxMessageSchema.Columns.Status}\" IN ({(int)OutboxMessageStatus.Pending}, {(int)OutboxMessageStatus.Failed})";

    /// <inheritdoc />
    protected override string RetryScheduledMessagesFilter =>
        $"\"{OutboxMessageSchema.Columns.Status}\" = {(int)OutboxMessageStatus.Failed} AND \"{OutboxMessageSchema.Columns.NextRetryAt}\" IS NOT NULL";

    /// <inheritdoc />
    protected override string CompletedMessagesFilter =>
        $"\"{OutboxMessageSchema.Columns.Status}\" = {(int)OutboxMessageStatus.Completed}";

    /// <inheritdoc />
    protected override void ApplyColumnTypes(EntityTypeBuilder<OutboxMessage> builder)
    {
        _ = builder.Property(m => m.Id).HasColumnType("uuid");
        _ = builder.Property(m => m.EventType).HasColumnType("character varying(500)");
        _ = builder.Property(m => m.Payload).HasColumnType("text");
        _ = builder.Property(m => m.CorrelationId).HasColumnType("character varying(100)");
        // "timestamp with time zone" (timestamptz) preserves UTC correctly.
        // Npgsql 6+ maps DateTimeOffset here by default, but being explicit avoids
        // ambiguity with older versions and documents the intent.
        _ = builder.Property(m => m.CreatedAt).HasColumnType("timestamp with time zone");
        _ = builder.Property(m => m.UpdatedAt).HasColumnType("timestamp with time zone");
        _ = builder.Property(m => m.ProcessedAt).HasColumnType("timestamp with time zone");
        _ = builder.Property(m => m.NextRetryAt).HasColumnType("timestamp with time zone");
        _ = builder.Property(m => m.RetryCount).HasColumnType("integer");
        _ = builder.Property(m => m.Error).HasColumnType("text");
        _ = builder.Property(m => m.Status).HasColumnType("integer");
    }
}
